version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - zip -r artifact.zip .
  post_build:
    commands:
      - aws elasticbeanstalk create-application-version --application-name iris --version-label v1.1 --source-bundle S3Bucket=elasticbeanstalk-us-east-1-457815361580	,S3Key=artifact.zip
      - aws elasticbeanstalk update-environment --environment-name Iris_env --version-label v1.1
